bot:
  clientid: node
  discord_token: none
  owner_id: 456217109236809748
  api: https://api.bowie-co.nz/api/v1
  hypixelapi_token: node
  status: for @Obsidion help
  default_prefix: /
channels:
  new_guild_channel: none
  upvote_channel: none
  bugs_channel: none
  feedback_channel: none
  bug_channel: none
discord_bot_lists:
  voting_enabled: false
  dbl_token: none
  bots4discord_token: none
  discordboats_token: none
  discordbotlist_token: none
  discodlabs_token: none
  botsondiscord_token: none
database:
  username: discord
  host: db
  password: reallystrongpassword
  database: discord
  port: 5432
redis:
  enabled: false
  host: none
  port: none
  password: none
stats:
  enabled: false
  statsd_host: "127.0.0.1"
  presence_update_timeout: 300
